openapi: 3.0.1
info:
  title: Workoutifier REST model
  description: 'This spec contains the shared model between web client and server from which the code is generated'
  version: 0.0.1
tags:
  - name: device
    description: Related to the ANT device itself
  - name: channel
    description: Related to channels
  - name: message
    description: related to messages
paths:
  /all:
    description: Dummy path which references all objects.
    get:
      responses:
        200:
          description: meh
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ApiMsg'
components:
  schemas:
    ApiMsg:
      type: object
      properties:
        request:
          enum: [ 'DeviceStatus' ]
        deviceStatusResponse:
          $ref: '#/components/schemas/DeviceStatusResponse'
    DeviceStatusResponse:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
    Device:
      type: object
      properties:
        test:
          type: string
        status:
          type: string
          enum: [ connected, disconnected ]